### ISSUE TITLE
Exposed YT api keys

### ISSUE THREAD

**Issue by ghost** [Caranea/song#3]
@Caranea
Hey it looks like you forgot the remove your api key from the repo
(if you dont know those are supposed to be private)
if you need help i can help you

Thanks!

**Comment by Caranea** [comment]
Hey @Arttast, 

thx for opening an issue. The API key is exposed on purpose. Let me explain:

1. Watch history is extremely sensitive information and I assumed people would be hesitant to use this app if their data was sent to any servers.
2. If I want to process users' data only in their devices, I need to store the API key in the client application
3. No matter what precautions would I take to obfuscate or cipher the key in the codebase, in the end it would need to be exposed in client 
4. Since the key is restricted and has a very small limit, there's no damage in it being exposed. If the request limit is reached, the application simply stops working until the next day

Hope it helps, 
Karolina

**Comment by ghost** [comment]
Yeah that makes sense forgot that
